name: Build and Run Test Application Workflow

on:
  schedule:
    - cron: '0 0 * * *' # (scheduled - once per day at midnight)
  pull_request: # (for every push to Pull Request)
    types: [opened, reopened, synchronize]
  workflow_dispatch:  # (to start the workflow manually)

jobs:
  build_project:
    name: Build Project
    uses: ./.github/workflows/build_esp_app.yml
# Disable this job if you don't use it for hardware testing
  test_project:
    name: Test Project
    uses: ./.github/workflows/test_esp_app.yml
    needs: build_project
